# Generated by Django 4.2.2 on 2023-09-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introductions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='photo',
        ),
    ]
