# Generated by Django 4.2.2 on 2023-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introductions', '0002_remove_introduction_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='kind',
            field=models.CharField(choices=[('preschool', 'Happy Preschool'), ('housing', 'Happy Housing'), ('farm', 'Happy Farm'), ('salon', 'Happy Hair Salon')], max_length=20),
        ),
    ]
