# Generated by Django 4.2.2 on 2023-09-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='owner',
        ),
        migrations.DeleteModel(
            name='photo',
        ),
    ]
