# Generated by Django 4.2.2 on 2023-09-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
